"""Extract the PyS60 API surface; resolve Khronos enums from PyOpenGL metadata."""

import pathlib
import re
import pprint
import OpenGL

root = pathlib.Path(__file__).resolve().parents[1]
source = (root / "pys60-1.4.5_src/ext/gles/glesmodule.cpp").read_text()
canvas = (root / "pys60-1.4.5_src/ext/glcanvas/glcanvasmodule.cpp").read_text()
constants = {}
for path in pathlib.Path(OpenGL.__file__).parent.joinpath("raw").rglob("*.py"):
    for name, value in re.findall(
        r"(?:IntConstant|Constant|_C)\(['\"]((?:GL|EGL)_\w+)['\"],\s*(0x[0-9a-fA-F]+|[0-9]+)\)",
        path.read_text(),
    ):
        constants[name] = int(value, 0)
constants.update(
    GL_OES_VERSION_1_0=1,
    GL_OES_VERSION_1_1=1,
    GL_OES_read_format=1,
    GL_OES_compressed_paletted_texture=1,
    EGL_DEFAULT_DISPLAY=0,
    EGL_NO_CONTEXT=0,
    EGL_NO_SURFACE=0,
    EGL_NO_DISPLAY=0,
)


def names(s, prefix):
    return sorted(
        set(
            re.findall(
                r'^\s*PyDict_SetItemString\(d,\s*"(' + prefix + r'_\w+)"', s, re.M
            )
        )
    )


gl_names = names(source, "GL")
egl_names = names(canvas, "EGL")
constants.update((n, 1) for n in gl_names if n.startswith("GL_OES_"))
missing = [n for n in gl_names + egl_names if n not in constants]
if missing:
    raise RuntimeError(missing)
methods = re.findall(
    r'\{"(\w+)",\s*\(PyCFunction\)',
    source[source.index("static const PyMethodDef gles_methods") :],
)
formats = {}
for name, body in re.findall(
    r'extern "C" PyObject \*gles_(\w+)\([^\n]*\)\s*\{(.*?)(?=\n(?:extern|PyObject|/\*|//)|\Z)',
    source,
    re.S,
):
    match = re.search(r'PyArg_ParseTuple\(args,\s*"([^":]+)', body)
    if match:
        formats[name] = match[1]
output = "# Generated by tools/generate_gles_manifest.py; PyS60 1.4.5 method/constant names.\n"
for key, value in [
    ("CONSTANTS", {n: constants[n] for n in gl_names}),
    ("EGL_CONSTANTS", {n: constants[n] for n in egl_names}),
    ("METHODS", methods),
    ("FORMATS", formats),
]:
    output += key + " = " + pprint.pformat(value, sort_dicts=True) + "\n"
(root / "Pys60_Simulator/pys60Core/_gles_manifest.py").write_text(output)
print(
    len(methods),
    "methods",
    len(gl_names),
    "GL constants",
    len(egl_names),
    "EGL constants",
)
